name: starfruit
description: A mathematical library extending and bettering provided dart and dart:math functions.
version: 0.2.1
homepage: https://github.com/AKushWarrior/starfruit
repository: https://github.com/AKushWarrior/starfruit
author: Aditya Kishore <akushwarrior@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.7