name: starfruit
description: A mathematical library extending and bettering provided dart and dart:math functions.
version: 1.0.0
homepage: https://github.com/AKushWarrior/starfruit
repository: https://github.com/AKushWarrior/starfruit
author: Aditya Kishore <akushwarrior@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  linalg: ^0.3.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.15.7
  should: ^1.0.0+4