name: starfruit
description: A mathematical library extending and bettering provided dart and dart:math functions.
version: 2.0.0+1
homepage: https://github.com/AKushWarrior/starfruit
repository: https://github.com/AKushWarrior/starfruit

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  linalg: ^0.4.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.0